version: '3.4'
services:
  db:
    image: mysql/mysql-server:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./mysql/dump:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: EqxM9tuOOsocoj
      MYSQL_DATABASE: dcsm
      MYSQL_USER: dcsm
      MYSQL_PASSWORD: dcsm
      TZ: "Europe/Moscow"
    ports:
      - 3309:3306
    container_name: mysql
    networks:
      - messenger_network
    
  es01:
    image: elasticsearch:7.9.2
    environment:
      - "ES_JAVA_OPTS=-Xms200m -Xmx2000m"
      - "TZ=Europe/Moscow"
      - discovery.type=single-node
      - node.name=es01
    restart: unless-stopped
    container_name: es01
    volumes:
      - ./docker-data/es/:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - messenger_network
      
  cerebro:
    image: lmenezes/cerebro
    container_name: cerebro
    restart: unless-stopped
    ports:
      - 9000:9000
    networks:
      - messenger_network
      
  rabbit:
    image: rabbitmq:3.9.8-management-alpine
    # Actually, we do not need hostname here, but rabbit configuration is linked to specific filename that contains hostname
    hostname: mes-rabbitmq
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./docker-data/rabbitmq/data/:/var/lib/rabbitmq/mnesia/
    networks:
      - messenger_network
      
  nginx-api:
    image: nginx:1.21.3
    #image: arm64v8/nginx
    container_name: nginx-api-messenger
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    ports:
      - 80:80
    volumes:
      - ./docker-config/nginx-api.conf:/etc/nginx/nginx.conf:ro
    networks:
      - messenger_network

  envoy:
    image: envoyproxy/envoy-dev:affac20e5089c4725eeb0f2de486b6580a07052d
    container_name: envoy-proxy
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    ports:
      - 10000:10000
    volumes:
      - ./docker-config/envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      - messenger_network

  redis:
    image: redis:6.2.6-alpine
    restart: unless-stopped
    container_name: redis
    volumes:
      - ./docker-data/es/:/usr/share/elasticsearch/data
    ports:
      - 6379:6379
    networks:
      - messenger_network

  minio:
    image: minio/minio
    restart: unless-stopped
    container_name: minio
    command:
      - 'server'
      - '/data'
      - --console-address
      - ":9001"
    volumes:
      - ./docker-data/minio:/data
    environment:
      - MINIO_BROWSER_REDIRECT_URL=https://calamity-s3-console.local.encamy.com
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
      - MINIO_SERVER_URL=https://calamity-s3.local.encamy.com
    ports:
      - 9010:9000
      - 9011:9001
    networks:
      - messenger_network

networks:
  messenger_network:
    external: true