version: '3.4'
services:
  mes-registration-service:
    build:
        context: ./src/dotnet
        dockerfile: Messenger.RegistrationServer/Dockerfile
    command: dotnet Messenger.RegistrationServer.dll
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    volumes:
      - ./docker-data/logs/registration-service:/app/logs/
      - ./docker-data/secrets/jwt_secret.secret:/app/jwt_secret.secret:ro
      - ./docker-data/secrets/mysql_secrets.json:/app/mysql_secrets.json:ro
      - ./docker-config/NLog.config:/app/NLog.config:ro
    networks:
      - messenger_network
        
  mes-auth-service:
    build:
        context: ./src/dotnet
        dockerfile: Messenger.AuthServer/Dockerfile
    command: dotnet Messenger.AuthServer.dll
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    volumes:
      - ./docker-data/logs/auth-service:/app/logs/
      - ./docker-data/secrets/jwt_secret.secret:/app/jwt_secret.secret:ro
      - ./docker-data/secrets/mysql_secrets.json:/app/mysql_secrets.json:ro
      - ./docker-config/NLog.config:/app/NLog.config:ro
    networks:
      - messenger_network
        
  mes-user-service:
    build:
        context: ./src/dotnet
        dockerfile: Messenger.UserServer/Dockerfile
    command: dotnet Messenger.UserServer.dll
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    volumes:
      - ./docker-data/logs/user-service:/app/logs/
      - ./docker-data/secrets/jwt_secret.secret:/app/jwt_secret.secret:ro
      - ./docker-data/secrets/mysql_secrets.json:/app/mysql_secrets.json:ro
      - ./docker-config/NLog.config:/app/NLog.config:ro
    networks:
      - messenger_network
        
  mes-chat-info-service:
    build:
        context: ./src/dotnet
        dockerfile: Messenger.ChatInfoServer/Dockerfile
    command: dotnet Messenger.ChatInfoServer.dll
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    volumes:
      - ./docker-data/logs/chat-info-service:/app/logs/
      - ./docker-data/secrets/jwt_secret.secret:/app/jwt_secret.secret:ro
      - ./docker-data/secrets/mysql_secrets.json:/app/mysql_secrets.json:ro
      - ./docker-config/NLog.config:/app/NLog.config:ro
    networks:
      - messenger_network

  mes-orchestrator-service:
    build:
        context: ./src/dotnet
        dockerfile: Messenger.Orchestrator/Dockerfile
    command: dotnet Messenger.Orchestrator.dll
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    volumes:
      - ./docker-data/logs/orchestrator-service:/app/logs/
      - ./docker-data/secrets/jwt_secret.secret:/app/jwt_secret.secret:ro
      - ./docker-data/secrets/mysql_secrets.json:/app/mysql_secrets.json:ro
      - ./docker-config/NLog.config:/app/NLog.config:ro
    networks:
      - messenger_network
      
  historical-messages-service:
    build:
      context: ./src/dotnet
      dockerfile: Messenger.HistoricalMessagesService/Dockerfile
    command: dotnet Messenger.HistoricalMessagesService.dll
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    volumes:
      - ./docker-data/logs/historical-messages-service:/app/logs/
      - ./docker-data/secrets/jwt_secret.secret:/app/jwt_secret.secret:ro
      - ./docker-data/secrets/mysql_secrets.json:/app/mysql_secrets.json:ro
      - ./docker-config/NLog.config:/app/NLog.config:ro
    networks:
      - messenger_network

  instant-messages-service:
    build:
      context: ./src/dotnet
      dockerfile: Messenger.InstantMessagingService/Dockerfile
    command: dotnet Messenger.InstantMessagingService.dll
    restart: unless-stopped
    deploy:
      replicas: 1
    environment:
      TZ: "Europe/Moscow"
    volumes:
      - ./docker-data/logs/instant-messages-service:/app/logs/
      - ./docker-data/secrets/jwt_secret.secret:/app/jwt_secret.secret:ro
      - ./docker-data/secrets/mysql_secrets.json:/app/mysql_secrets.json:ro
      - ./docker-config/NLog.config:/app/NLog.config:ro
    networks:
      - messenger_network

  message-service:
    build:
      context: ./src/dotnet
      dockerfile: Messenger.MessageService/Dockerfile
    command: dotnet Messenger.MessageService.dll
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    deploy:
      replicas: 1
    volumes:
      - ./docker-data/logs/message-service:/app/logs/
      - ./docker-data/secrets/jwt_secret.secret:/app/jwt_secret.secret:ro
      - ./docker-data/secrets/mysql_secrets.json:/app/mysql_secrets.json:ro
      - ./docker-config/NLog.config:/app/NLog.config:ro
    networks:
      - messenger_network
      
  subcribing-service:
    build:
      context: ./src/dotnet
      dockerfile: Messenger.SubscribingService/Dockerfile
    command: dotnet Messenger.SubscribingService.dll
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    deploy:
      replicas: 1
    volumes:
      - ./docker-data/logs/subcribing-service:/app/logs/
      - ./docker-data/secrets/jwt_secret.secret:/app/jwt_secret.secret:ro
      - ./docker-data/secrets/mysql_secrets.json:/app/mysql_secrets.json:ro
      - ./docker-config/NLog.config:/app/NLog.config:ro
    networks:
      - messenger_network

networks:
  messenger_network:
    external: true